services:
  plantify-app:
    build: .
    container_name: plantify_backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/db_plantify?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 11082003
    restart: always

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 11082003
      MYSQL_DATABASE: db_plantify
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  mysql_data:
